/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorwindow;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import databasereader.AbstractReader;
/**
 *
 * @author Will_and_Sara
 */
public class Window extends javax.swing.JFrame implements PropertyChangeListener{
    private javax.swing.JScrollPane FTSP;
    private javax.swing.JScrollPane VTSP;
    private AbstractReader reader;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        //initialize the test data, it should be a series of column names, their output types, and some sample data (the first row of a dbf)
        reader = new databasereader.DBFReader("/Users/Will_and_Sara/Desktop/RUS_Structures.dbf");
        
        //String[] cols = {"A","B","C"};
        //ParseTreeNodes.TypeEnum[] types = {ParseTreeNodes.TypeEnum.DOUBLE,ParseTreeNodes.TypeEnum.STRING,ParseTreeNodes.TypeEnum.BOOLEAN};
        //Object[] SampleData = {2.0,"exhibit B",true};

        //create a function tree, this allows the user to see the available functions, quiery their help, and insert their syntax.

        FunctionTree FT = new FunctionTree();
        FTSP = new javax.swing.JScrollPane(FT);
        FTSP.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        FTSP.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        FTSP.setSize(200,200);
        FTSP.setLocation(220,10);
        
        //create a varable tree, this will show the user the availabe variables to include in their computation, currently it is simply the name of the column.  this can have the type added as a tooltip or something.
        VariableTree VT = new VariableTree(reader.getColumnNames());
        VTSP = new javax.swing.JScrollPane(VT);
        VTSP.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        VTSP.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        VTSP.setSize(200,200);
        VTSP.setLocation(10,10);

        //create an expression window, the expression window does the work, it needs all of the initial data so that the expression can be tested for validity, and so that example output can be shown.
        ExpressionWindow EW = new ExpressionWindow(reader.getColumnNames(),ReaderTypesToParserTypes(),reader.getRow(0));
        EW.setSize(404,200);
        EW.setLocation(12,220);

        //this listener allows the calculator to show the expression and output if the designer so chooses.
        EW.addPropertyChangeListener(this);

        //This listener allows the function tree to insert syntax to the expression window.
        FT.addPropertyChangeListener(EW);

        //this listener allows the variable tree to insert column nmaes with the correct syntax into the expression window.
        VT.addPropertyChangeListener(EW);

        this.getContentPane().add(EW);
        this.getContentPane().add(FTSP);
        this.getContentPane().add(VTSP);
        

    }
    private ParseTreeNodes.TypeEnum[] ReaderTypesToParserTypes(){
        ParseTreeNodes.TypeEnum[] output = null;
        if(null!=reader){
            output = new ParseTreeNodes.TypeEnum[reader.getNumberOfColumns()];
            for(int i = 0; i <reader.getNumberOfColumns();i++){
                switch(reader.getColumnTypes()[i]){
                    case STRING:
                        output[i] = ParseTreeNodes.TypeEnum.STRING;
                        break;
                    case BOOLEAN:
                        output[i] = ParseTreeNodes.TypeEnum.BOOLEAN;
                        break;
                    case INT:
                        output[i] = ParseTreeNodes.TypeEnum.LONG;
                        break;
                    case DOUBLE:
                        output[i] = ParseTreeNodes.TypeEnum.DOUBLE;
                        break;
                    default:
                        output[i] = ParseTreeNodes.TypeEnum.STRING;
                        break;
                }
            }
        }
        return output;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpressionLabel = new javax.swing.JLabel();
        ResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExpressionLabel.setText("Expression");

        ResultLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExpressionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExpressionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Window T;
                T = new Window();
                T.pack();
                T.setVisible(true);
            }
        });
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if("Tree".equals(evt.getPropertyName())){
            ParseTreeNodes.ParseTreeNode tree = (ParseTreeNodes.ParseTreeNode)evt.getNewValue();
            ExpressionLabel.setText(tree.ToString());
            ResultLabel.setText(tree.Evaluate().Result().toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExpressionLabel;
    private javax.swing.JLabel ResultLabel;
    // End of variables declaration//GEN-END:variables
}
